version: '3.9'

services:
  aks-startup-dockeragent-1:
    image: aks-startupdacr.azurecr.io/aks-startup-dockeragent:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}      
        AKS-STARTUP_AZURE_DEVOPS_TOKEN: ${AKS-STARTUP_AZURE_DEVOPS_TOKEN}
    restart: always
    container_name: aks-startup-dockeragent-1
    environment:
      - EXAMPLE_CONFIG=/test/test
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - KUBECONFIG=/kubeconfig/config
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - AKS-STARTUP_AZURE_DEVOPS_TOKEN=${AKS-STARTUP_AZURE_DEVOPS_TOKEN}
      - AZP_URL=${AZP_URL}
      - AZP_TOKEN=${AZP_TOKEN}
      # - AZP_AGENT_NAME=mydockeragent
      # - GPG_TTY=/dev/pts/3
      # - GCM_CREDENTIAL_STORE=cache
      # - GCM_CREDENTIAL_CACHE_OPTIONS="--timeout 9999999"
    volumes:
      - "vscode_server_extensions:/root/.vscode-server/extensions"
      - "/var/run/docker.sock:/var/run/docker.sock"
    # ports: 
    #   - 5003:5003
    networks:
      - aks-startup_common_network
  aks-startup-dockeragent-2:
    image: aks-startupdacr.azurecr.io/aks-startup-dockeragent:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}      
        AKS-STARTUP_AZURE_DEVOPS_TOKEN: ${AKS-STARTUP_AZURE_DEVOPS_TOKEN}
    restart: always
    container_name: aks-startup-dockeragent-2
    environment:
      - AZP_URL=${AZP_URL}
      - AZP_TOKEN=${AZP_TOKEN}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"      
    networks:
      - aks-startup_common_network
  aks-startup-dockeragent-3:
    image: aks-startupdacr.azurecr.io/aks-startup-dockeragent:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}      
        AKS-STARTUP_AZURE_DEVOPS_TOKEN: ${AKS-STARTUP_AZURE_DEVOPS_TOKEN}
    restart: always
    container_name: aks-startup-dockeragent-3
    environment:
      - AZP_URL=${AZP_URL}
      - AZP_TOKEN=${AZP_TOKEN}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"      
    networks:
      - aks-startup_common_network
networks:
  aks-startup_common_network:
    name: aks-startup_common_network
    external: true

volumes:
  vscode_server_extensions: {}