name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - terraform-backend/*

pool: Default

# Load secrets from Key Vault
variables:
  - group: aks-startup
  - name: tfFolder  # Name of folder to run terraform commands
    value: terraform-backend
  - name: workingDirectoryFolder  # Name of folder to run terraform commands
    value: $(System.DefaultWorkingDirectory)/$(tfFolder)/

steps:

- bash: |
    ls -al
  displayName: List files in $(workingDirectoryFolder)
  workingDirectory: $(workingDirectoryFolder)
  failOnStderr: true

- bash: |
    echo "terraform init" /
    terraform init -input=false
  displayName: Terraform Init
  workingDirectory: $(workingDirectoryFolder)
  failOnStderr: true
  env:
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_CLIENT_ID:       $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET:   $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID:       $(ARM_TENANT_ID)

- bash: |
    echo "terraform plan" /
    terraform plan -input=false
  displayName: Terraform Plan
  workingDirectory: $(workingDirectoryFolder)
  failOnStderr: true
  env:
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_CLIENT_ID:       $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET:   $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID:       $(ARM_TENANT_ID)

- bash: |
    echo "terraform apply" /
    terraform apply -auto-approve -input=false
  displayName: Terraform Apply
  workingDirectory: $(workingDirectoryFolder)
  failOnStderr: true
  env:
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_CLIENT_ID:       $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET:   $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID:       $(ARM_TENANT_ID)